### ISSUE TITLE
Does the module have a binary to connect RabbitMQ?

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#14]
Hi,
can I start it as an amqp service?

Regards,
Jan

**Comment by Bystroushaak** [comment]
Yes. There is script in edeposit.amqp; https://github.com/edeposit/edeposit.amqp/blob/master/bin/edeposit_amqp_pdfgend.py

**Comment by Bystroushaak** [comment]
Also the logo was just added: https://dl.dropboxusercontent.com/u/11891854/tmp/review_test.pdf :)

**Comment by jstavel** [comment]
Great! Thank you.

**Comment by jstavel** [comment]
Hi!
I installed edeposit.amqp and edeposit.amqp.pdfgen.
There is no bin edeposit_amqp_pdfgen.py.

**Comment by Bystroushaak** [comment]
Try it now. Also it is not ``edeposit_amqp_pdfgen.py``, but ``edeposit_amqp_pdfgend.py`` (with **d**).

**Comment by jstavel** [comment]
I got into the problem I reported at the beginning.
Command python setup.py egg_info failed with error code 1 in /home/jan/lib/edeposit/build/edeposit.amqp.pdfgen
Storing complete log in /home/jan/.pip/pip.log
jan@jan-XPS-L421X:~/lib/edeposit$ ./bin/pip install --upgrade edeposit.amqp.pdfgen
Downloading/unpacking edeposit.amqp.pdfgen from https://pypi.python.org/packages/source/e/edeposit.amqp.pdfgen/edeposit.amqp.pdfgen-0.2.0.tar.gz#md5=4d2b63e5ac72eb3bd39a384a2d8e44bf
  Downloading edeposit.amqp.pdfgen-0.2.0.tar.gz (288kB): 288kB downloaded
  Running setup.py egg_info for package edeposit.amqp.pdfgen
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/jan/lib/edeposit/build/edeposit.amqp.pdfgen/setup.py", line 99, in <module>
        cmdclass={'sdist': BuildSphinx}
      File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "<string>", line 11, in replacement_run
      File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load
        return self.resolve()
      File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ImportError: No module named version
    Complete output from command python setup.py egg_info:
    running egg_info

creating pip-egg-info/edeposit.amqp.pdfgen.egg-info

writing requirements to pip-egg-info/edeposit.amqp.pdfgen.egg-info/requires.txt

writing pip-egg-info/edeposit.amqp.pdfgen.egg-info/PKG-INFO

writing namespace_packages to pip-egg-info/edeposit.amqp.pdfgen.egg-info/namespace_packages.txt

writing top-level names to pip-egg-info/edeposit.amqp.pdfgen.egg-info/top_level.txt

writing dependency_links to pip-egg-info/edeposit.amqp.pdfgen.egg-info/dependency_links.txt

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/jan/lib/edeposit/build/edeposit.amqp.pdfgen/setup.py", line 99, in <module>

    cmdclass={'sdist': BuildSphinx}

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "<string>", line 11, in replacement_run

  File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2310, in load

    return self.resolve()

  File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2316, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

ImportError: No module named version

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/jan/lib/edeposit/build/edeposit.amqp.pdfgen
Storing complete log in /home/jan/.pip/pip.log
jan@jan-XPS-L421X:~/lib/edeposit$ 

Could you try to reinstall edeposit.amqp.pdfgen at yout virtualenv?

No binary appeared.

**Comment by Bystroushaak** [comment]
The script is in edeposit.amqp package, not in edeposit.amqp.pdfgen. I did tried it and works as expected.

I've tried it in virtualenv at my home computer and it also works as expected. I am using everywhere ubuntu, so this may be the difference.

**Comment by Bystroushaak** [comment]
See edeposit/edeposit.amqp/issues/39 for details.
