### ISSUE TITLE
list index out of range exception

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.pdfgen#17]
I have put resources by hand.
The response is:

headers:	
exception_type:	<type 'exceptions.IndexError'>
exception:	list index out of range
traceback:	Traceback (most recent call last):
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 141, in onMessageReceived
uuid
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/__init__.py", line 44, in reactToAMQPMessage
get_contract(**message._asdict())
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/specialization.py", line 74, in get_contract
open(_resource_context("style.json")).read(),
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/translator.py", line 70, in gen_pdf
pdf = _init_pdf(f.name, header, footer)
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/edeposit/amqp/pdfgen/translator.py", line 44, in _init_pdf
footer=footer
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 186, in __init__
self.loadStyles(stylesheets)
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 281, in loadStyles
def_dpi=self.def_dpi)
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/rst2pdf/styles.py", line 352, in __init__
fontList = findfonts.autoEmbed(style[key])
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/rst2pdf/findfonts.py", line 273, in autoEmbed
f = findFont(fname)
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/rst2pdf/findfonts.py", line 154, in findFont
loadFonts()
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/rst2pdf/findfonts.py", line 65, in loadFonts
font = TTFontFile(ttf)
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/reportlab/pdfbase/ttfonts.py", line 407, in __init__
self.extractInfo(charInfo)
File "/home/jan/lib/edeposit/local/lib/python2.7/site-packages/reportlab/pdfbase/ttfonts.py", line 745, in extractInfo
glyph = glyphs[SH[0].idRangeOffset+(unichar-SH[0].firstCode)]
IndexError: list index out of range
exception_name:	IndexError
UUID:	{"context_UID": "4927306b47bc477ba988f64412339612", "session_data": {"id": "zlinske-nakladatelstvi"}}
content_type:	application/text

**Comment by Bystroushaak** [comment]
Can you try it now please?

**Comment by jstavel** [comment]
The problem occurs just when processing the first request.
All next requests are processed well.

**Comment by jstavel** [comment]
upgrade did not help.
So the first attempt to generate pdf file finishes with error.
Next ones finish with success.

**Comment by Bystroushaak** [comment]
This is really strange. I was not able to replicate the bug. From the stacktrace it looks like the bug is somewhere in reportlab.

**Comment by Bystroushaak** [comment]
The bug is not manifesting anymore.
